export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";
export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const DELETE_USER = "DELETE_USER";

export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const LIKE_PRODUCT = "LIKE_PRODUCT";
export const FETCH_PRODUCTS_BY_ID = "FETCH_PRODUCTS_BY_ID";
export const ADD_DISCOUNT = "ADD_DISCOUNT";

export const FETCH_ORDERS = "FETCH_ORDERS";
export const ADD_ORDER = "ADD_ORDER";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
export const FETCH_ORDER_BY_EMAIL = "FETCH_ORDER_BY_EMAIL";
